bankofcanada/ModelBaseEcon.jl

Project.toml, src/steadystate.jl, src/variables.jl, test/runtests.jl
* In the steady state solver we now have `Vt = exp(V#lvl + t * V#slp)`
* `m.shift` has immediate effect (no need to re-call `@initialize m`)
* `printsstate()` shows type of variables and comments
* `@steadystate` with `@log`-variable now replaces `V` with `exp(V#lvl)`
* `@steadystate` unblocks expressions
=> Log-vars redesign

src/variables.jl
On Julia 1.7+, the Model fails to initialize because the variables are no longer matched to their equivalents in the equations. 
This is caused by a breaking [change ](https://github.com/JuliaLang/julia/pull/40935/commits/c47754e2598858927118f2f7474354f306d6a6eb) in Julia between versions 1.6 and 1.7 which optimized the one-argument hash function for symbols. 
Since the one-argument hash function for symbols now differs from the two-argument one, it is necessary to add the Base.hash equivalent for the one-argument form.
For a bit more context see here: https://github.com/JuliaLang/julia/issues/44007
=> Fix ModelVariable hash on Julia 1.7+

.github/workflows/main.yml, Project.toml
This is a placeholder to trigger code coverage scripts.
=> Code coverage

src/evaluation.jl
takes the time to precompile FRB_US model from 38s to 35s.
This uses a local counter per module instead of the global one now but I think that should be ok.
=> simplify computing equation numbers in a module

src/evaluation.jl
This takes the time to precompile the FRB_US model from 52s to 38s.
This also takes the load time of the precompiled FRB_US model from 5.5s to 0.62s which is a bigger change than I expected.
=> Avoid creating a new generator to create `LittleDict` for every equation

src/model.jl, src/parameters.jl, test/runtests.jl
This commit fixes an issue where deepcopies of models would exhibit behavior different from the original due to an incomplete implementation of `deepcopy_internal` for Parameters which did not update the stackdict. This resulted in broken references buried within the functions of the ssequations and the evaldata object. 
Additional tests were also added.
The text below is obsolete, it explains some of the changes made in the earlier commits, undone in the latest commit.
---
**Description of fix in earlier commits.**
In the SteadyStateData, the broken reference is to the model itself within an `SSEqnData` object which gets created for the creation of the resid functions, but is discarded and subsequently no longer exists outside of those functions.
```
function sseqn_resid_RJ(s::SSEqnData) …
```
=> Fix deepcopy of Parameters

src/ModelBaseEcon.jl, src/equation.jl, src/model.jl, test/runtests.jl
This PR removes trailing whitespace from files which form part of other current PRs. If merged, it will make the diff on these other files easier to read/understand.
A separate PR will be created for removing trailing whitespace from all source files.
=> Remove training whitespace on select files

src/ModelBaseEcon.jl, src/evaluation.jl, src/precompile.jl
**Note**: This PR is made on top of https://github.com/bankofcanada/ModelBaseEcon.jl/pull/37
Share the ForwardDiff tag between models and fix a typo in precompilation
Currently, every model gets its own ForwardDiff tag which means that every model
also have a unique type of their dual numbers. This causes every function called
with dual numbers to have to be recompiled for every model.
In this PR, we define a shared tag in ModelBasedEcon that all models use.
This means that we can push the precompile generation for many functions
from the model into ModelBaseEcon itself which changes the cost of them
from O(1) to O(n_models). This requires moving  `MAX_CHUNK_SIZE` from
being dynamic to a compile-time constant but looking at the numbers below,
it seems worth it.
This PR also corrects a …
=> Share ForwardDiff tags between models 

src/metafuncs.jl, src/model.jl, test/runtests.jl
Julia parses `a + b + c + ...` as `+(a, b, c, ...)` which ends up calling a function with a variable number of arguments (`afoldl`). This means that we compile many functions of the following kind:
```julia
precompile(Tuple{typeof(Base.afoldl), typeof(Base.:(+)), Vararg{ForwardDiff.Dual{f, Float64, 4}, 30}})
precompile(Tuple{typeof(Base.afoldl), typeof(Base.:(+)), Vararg{ForwardDiff.Dual{f, Float64, 4}, 29}})
precompile(Tuple{typeof(Base.afoldl), typeof(Base.:(+)), Vararg{ForwardDiff.Dual{f, Float64, 4}, 13}})
precompile(Tuple{typeof(Base.afoldl), typeof(Base.:(+)), Vararg{ForwardDiff.Dual{f, Float64, 4}, 12}})
```
since this n-arg structure is commonly introduced by e.g `@movav`.
This PR introduces a function that can be applied to an expression that splits up an n-arg expression like …
=> avoid calling `+` with variable number of arguments

src/model.jl
Looking up the index for a single variable is quite expensive since
we need to find that variable in a vector. The current method ended up
calling `indexin` which is not optimized well for finding a single value
since it does quite a bit of expensive stuff under the hood (like creating
a dictionary).
Instead, in this PR, we precompute a variable => index mapping for all variables
which is done via a simple loop and then use that mapping when an index is needed.
This takes the time for solving the FRB-US model (following the tutorial in TutorialsEcon and using
the `@btime` macro from BenchmarkTools.jl) from
```julia
julia> @btime simulate(m, p_0, ed_0; verbose=true, tol=1e-12);
472.368 ms (1646933 allocations: 3.80 GiB)
```
to
```julia
julia> @btime simulate(m, p_0, ed_0; verbose=true, …
```
=> Precompute looking up indices for all variables in `update_auxvars`

src/evaluation.jl, src/model.jl
In https://github.com/bankofcanada/ModelBaseEcon.jl/pull/48 it was described how the non typed `params` dictionary in `EquationEvaluator` leads to type instabilities and bad performance.
The suggestion in that PR was to limit the "type space" that parameters can take.
It is however not clear what type space this should be since users can in theory define arbitrary types in their model.
This PR thus takes a different approach where equations involving parameters gets an extra function where that function has the type parameters as arguments.
The tradeoff then is the cost of a dynamic dispatch to the extra function vs having things be well typed inside that function.
Julia's dynamic dispatch is quite fast and from benchmarks this seems to be a good gain.
Running the benchmark
```julia …
```
=> use a function barrier for evaluating equations with parameters 

src/export_model.jl
This PR includes two changes
1. Exported options now prepended with `model.options.` instead of simply `model.`. 
2. The exported model now uses the StateSpaceEcon package if there is a final conditions option set.
Note that the export of flags was not changed.
=> prepend exported options with model.options.

src/model.jl, test/runtests.jl
This is a small fix that adds an option to the model `unused_varshks` which takes a vector of symbols (or in theory another iterable).
Any symbols within this vector will no longer throw a warning when `@initialize` or `@reinitialize` is called and the corresponding variable is not being used in the model equations.
This solves an issue when some variables are needed for the steadystate but are not present in the model equations.
Tests were also added to verify this behavior.
We may want to change the naming convention here.
=> Add option to suppress unused varshks warning

src/abstract.jl, src/evaluation.jl, src/model.jl, src/steadystate.jl, test/runtests.jl
The model change syntax can introduce excessive function generation if the model changes are run repeatedly; we will generate new `resid`, `RJ`, and `resid_param` functions and evaluate and precompile these every time an equation is changed even if we are just repeatedly running the same model change block. 
This fix introduces a new variable `_expression_functions_map` at the current modelmodule level (i.e. LENS or Main) which simply keeps track of the generated functions and indexes them by the expression used in the equation from which they were generated.
This is a relatively naïve approach as non-functional changes to the expression would lead to a new entry in the list, but it does fix the issue of generating new unnecessary functions when repeatedly running the same code. …
=> Avoid regeneration of functions for known equations

src/model.jl, src/steadystate.jl, test/runtests.jl
update `@equations` and `@steadystate` to handle equations
with docstrings and name tags
Fixes #58
=> Handle equations with docstrings and name tags

src/linearize.jl, src/metafuncs.jl, src/model.jl, src/steadystate.jl, test/runtests.jl
=> @lag works correctly with  multiple indices

src/model.jl, test/runtests.jl
=> Fix two problems with if-statements in equations

src/model.jl, test/runtests.jl
We had a parsing error when the entire equation was wrapped inside parentheses. `ModelBaseEcon.jl` was not recognizing it as an expression. We covered all four cases: with and without tags, with and without `@lin`.
For instance, the model below shows all 4 cases that failed before:
```julia
module A
using ModelBaseEcon
const model = Model()
@variables model x
@equations model begin
:EQ_x1 => (x[t] = 0)
(x[t] = 0)
:EQ_x1 => (@lin x[t] = 0)
(@lin x[t] = 0)
end
@initialize(model)
end
```
=> Fix issues with equation parentheses

src/evaluation.jl, test/runtests.jl
We add a function to evaluate the residuals of an equation: `eval_equation()`.
=> eval_equation and tests

.github/workflows/main.yml, src/model.jl, test/auxsubs.jl, test/runtests.jl
Model checks done in `@initialize` are `@reinitialize` are now done in a new function `checkmodel`. This reduces code duplication.
Also, adding a new check that model has the saem number of equations and (non shock, non exog) variables.
=> Adding function `checkmodel`. 
